sudo: required

language: java

services:
  - docker

# --abort-on-container-exit tells Docker to stop all services once one container has finished
after_success:
  - docker-compose up --abort-on-container-exit